#/home/travis/build/yii2mod/base/tests/codeception/config/functional.php

language: php

php:
  - 5.4

env:
  - CUBRID_VERSION=9.3.0/CUBRID-9.3.0.0206 CUBRID_PDO_VERSION=9.3.0.0001

matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
#    - cubrid # caching cubrid breaks the build on a regular basis and has nearly no speedup
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - pwd
  - mysql -e 'CREATE DATABASE yii2base;';
  - composer create-project
  - chmod +x yii && ./yii migrate --interactive=0
  - vendor/bin/codecept build
  - cd web && php -S localhost:8080 > /dev/null 2>&1 &
  - vendor/bin/codecept run --coverage --coverage-xml --coverage-html

after_script:
  - cd ~/build/yii2mod/base/
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
